from fastapi import FastAPI
from database import models
from database.database import engine
from routers import post
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()
app.include_router(post.router)

models.Base.metadata.create_all(engine)

#static file(already exits) are sent to user without changing ->not generated by python simply stored in disk
#mount means connect to url,whith out mount fast api does not know what image means.
app.mount('/images',StaticFiles(directory="images"),name='images')  # name is internal reference for fastapi

#CORS-Cross-Origin Resource Sharing is a browser security rule
#which websites are allowed to access your FastApi Application
origins = [
    'https://fastapi-blog-frontend.onrender.com/'   # React app runs at 3000
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials =True,
    allow_methods=['*'],
    allow_headers=['*']
)